name: Deploy Express Backend to cPanel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Deploy to cPanel (backend)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.CPANEL_USERNAME }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }} # /home/user/backend
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          eval "$(ssh-agent -s)"
          ssh-add key.pem

          # Check REMOTE_PATH isn't dangerously empty or root
          if [[ -z "$REMOTE_PATH" || "$REMOTE_PATH" == "/" || "$REMOTE_PATH" == "/home/$USERNAME" ]]; then
            echo "❌ Aborting deploy: Unsafe REMOTE_PATH"
            exit 1
          fi

          # Upload backend source code
          rsync -avz --delete-after -e "ssh -p 21098  -o StrictHostKeyChecking=no" . $USERNAME@$SERVER_IP:$REMOTE_PATH

          # Stop Node.js app using CloudLinux command
          ssh -p 21098 -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP << 'ENDSSH'
            cloudlinux-selector stop --json --interpreter nodejs --user alottpil --app-root /home/alottpil/irelandmuslimsapi.alotaki.com || true
            echo "✅ Node.js app stopped"
          ENDSSH

          # Restart backend on server
          ssh -p 21098  -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP << 'ENDSSH'

            source /home/alottpil/nodevenv/irelandmuslimsapi.alotaki.com/14/bin/activate && cd /home/alottpil/irelandmuslimsapi.alotaki.com
            npm install --omit=dev

            # Stop the app (if any old process is running) and start it again
            pkill -f "node index.js" || true
            nohup node index.js > out.log 2>&1 &

            # Check if the Node.js process is running
            sleep 5  # Wait for a few seconds to allow the process to start
            if pgrep -f "node index.js" > /dev/null; then
              echo "✅ Node.js app successfully restarted"
            else
              echo "❌ Failed to start Node.js app"
              exit 1
            fi
          ENDSSH

          # Start Node.js app using CloudLinux command
          ssh -p 21098 -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP << 'ENDSSH'
            cloudlinux-selector start --json --interpreter nodejs --user alottpil --app-root /home/alottpil/irelandmuslimsapi.alotaki.com
            echo "✅ Node.js app started"
          ENDSSH
