name: Deploy Express Backend to cPanel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Deploy to cPanel (backend)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.CPANEL_USERNAME }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }} # /home/user/backend
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          eval "$(ssh-agent -s)"
          ssh-add key.pem

          # Check REMOTE_PATH isn't dangerously empty or root
          if [[ -z "$REMOTE_PATH" || "$REMOTE_PATH" == "/" || "$REMOTE_PATH" == "/home/$USERNAME" ]]; then
            echo "❌ Aborting deploy: Unsafe REMOTE_PATH"
            exit 1
          fi

          # Upload backend source code
          rsync -avz --delete-after -e "ssh -p $SSH_PORT -o StrictHostKeyChecking=no" . $USERNAME@$SERVER_IP:$REMOTE_PATH

          # Restart backend on server
          ssh -p $SSH_PORT -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP << 'ENDSSH'
            source /home/alottpil/nodevenv/irelandmuslimsapi.alotaki.com/14/bin/activate && cd /home/alottpil/irelandmuslimsapi.alotaki.com
            npm install --omit=dev
            pkill -f "node index.js" || true
            nohup node index.js > out.log 2>&1 &
          ENDSSH
